# Generated by Django 4.2 on 2024-12-21 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_description_note_content_remove_note_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='notes/'),
            preserve_default=False,
        ),
    ]
